### ISSUE TITLE
Hello, help on build

### ISSUE THREAD

**Issue by neatlife** [SilverMarcs/GPTalks#1]
hello, I try to compile, but get error cant resolve
package dependency ./OpenAi is local package that cant find on git
so I try replace it with https://github.com/MacPaw/OpenAI

It compile success but run into error:
dyld[90690]: Symbol not found: _$s21DeveloperToolsSupport7PreviewV7SwiftUIE_6traits4bodyACSSSg_AA0D5TraitVyAC10ViewTraitsOGdAD0J0_pyScMYcctcfC
  Referenced from: <7B6D6C28-7D62-33A1-800B-FAEDAD4BAD2C> /Users/xxx/Library/Developer/Xcode/DerivedData/GPTalks-ctpjthuqrfukfsexruailklzdhmd/Build/Products/Debug/GPTalks.app/Contents/MacOS/GPTalks
  Expected in:     <30986795-2C79-339C-AF7C-BDE00A7D65E2> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI

**Comment by SilverMarcs** [comment]
Hi, my bad, the project was still pointing towards my local custom repo of the MacPaw OpenAI project. I have just pushed a commit to point towards a public repository for the custom package. Can you try to pull again or reclone?
