### ISSUE TITLE
Feature Request: Support using Enter to submit message instead of Shift + Enter

### ISSUE THREAD

**Issue by tisfeng** [SilverMarcs/GPTalks#19]
Applications like ChatGPT directly submit messages using Enter, and I have completely gotten used to this way of use. Can GPTalks also support it?

**Comment by SilverMarcs** [comment]
Hey! Right now, the shortcut to send is set to Command + Enter on MacOS. I used to have it set to just Enter, but I often use the app for coding, and needing Shift + Enter for new lines everytime was a bit tedious so I opted for just Enter for newlines. That said, I totally get that most people expect Enter to send, so I’m planning to add a setting soon where you can choose. On iOS, Enter should always send by default. Thanks for the feedback!

**Comment by tisfeng** [comment]
Great!

**Comment by tisfeng** [comment]
Hello, the latest feature branch code can't run, can you check it?

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/5e5324a8-e008-4688-a155-ab239e035e33">

**Comment by SilverMarcs** [comment]
Can you pull again? Perhaps better if you delete the entire folder and clone from git again

**Comment by tisfeng** [comment]
I just git pull, it's ok now 🙂
