### ISSUE TITLE
Feature Request:  Support Markdown custom Theme

### ISSUE THREAD

**Issue by tisfeng** [SilverMarcs/GPTalks#20]
Currently, the default theme is `atom`, I prefer `github`, but it cannot be changed. 

I noticed that MarkdownWebView seems to support multiple themes, can GPTalks support this as well?

**Comment by SilverMarcs** [comment]
I think the current version of GPTalks on the main branch does support multiple themes. Need to go into Settings > Markdown to change the current theme. This is only for the MacOS version of the app.

Can't remember if the iOS version has it as well, but I'll check and add back accordingly

**Comment by tisfeng** [comment]
Good
