### ISSUE TITLE
The Command + K shortcut function is missing

### ISSUE THREAD

**Issue by quanuanc** [SilverMarcs/GPTalks#22]
I am building this app using the feature branch of this repo. Don't know since when the Command + K shortcut key can no longer be used. Has this shortcut key function been removed?

**Comment by SilverMarcs** [comment]
I recently removed the context reset feature (triggered by CMD + K) since I was barely using it and it added a fair bit of complexity. I may consider bringing it back later though

**Comment by SilverMarcs** [comment]
I re-added this to feature branch. Might be buggy, haven't tested much

**Comment by quanuanc** [comment]
Thanks a bunch! This feature is super helpful when I want to start a new topic without creating a whole new chat.
